### ISSUE TITLE
Information about wrong conversion

### ISSUE THREAD

**Issue by luca2125** [MikeG621/YOGEME#51] opened 2021-03-17 15:49 UTC
Hi Mike,

Please excuse me for disturb again.

I tring to fix some wrong conversion on xwing.

Attached there is the original version and the converted version.

[xwing_mission_2.zip](https://github.com/MikeG621/YOGEME/files/6157665/xwing_mission_2.zip)

In the briefing there are wrong text but I think there is an error in some tags (Here there is no clear text tag).

The message events are shorter but in the briefing I see the some result but the summary show only one message.

Do you known where there is the error ?

Thanks !

**Comment by MikeG621** [comment] 2021-03-17 23:58
Looks like the problem is in the briefing conversion; it completely stopped
processing the events part of the way through.  I didn't write that
routine, so I'll need to dig into why it stopped.
--

**Comment by luca2125** [comment] 2021-03-18 08:45
Thank you Mike !!

**Comment by luca2125** [comment] 2021-03-20 20:24
Hi Mike,

I the meamtime I have checked the source code:

![event missing](https://user-images.githubusercontent.com/55355625/111884454-037b3900-89c2-11eb-996e-9e8c9c93c39e.png)

For what I see the cause of error seem the event "wait for click" that probably don't exit in xwa and exist only with xw.

A possible solution (if there is no better alternative) can be replace it with "page break".

I'am sure exist a better solution but I don't known what could be ...

Best Regards

Marco

**Comment by MikeG621** [comment] 2021-03-24 03:16
Yes, the original author already has a mechanism to map the events during
platform conversions, but did not include that one.  Once I added that it
works fine.
--

**Comment by luca2125** [comment] 2021-03-24 07:35
Thank you Mike, I wating for your update.

**Comment by MikeG621** [comment] 2021-03-24 23:40
Fixed in [Platform v5.2](https://github.com/MikeG621/Platform/releases/tag/v5.2) and later releases.  Download that and put it in YOGEME's /bin/ directory.

**Closed by MikeG621** 2021-03-24 23:40 UTC

**Comment by luca2125** [comment] 2021-03-25 08:31
Thank you Mike I will do.
